name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"
      - name: Deploy Github pages
        run: mkdocs gh-deploy --force
